env:
  node: true
  es2020: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  impliedStrict: true
plugins:
  - '@typescript-eslint'
  - jest
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
