server:
  url: SERVER_URL
  port: SERVER_PORT
  temp: SERVER_TEMP

betaseries:
  timeoutInSeconds: BETASERIES_TIMEOUT
  client:
    plexAccount: PLEX_ACCOUNT
    clientId: BETASERIES_CLIENTID
    clientSecret: BETASERIES_CLIENTSECRET
  clients:
    __name: BETASERIES_CLIENTS
    __format: yml
