server:
  # url: ''
  port: 12000
  temp: /tmp/plex-betaseries-webhook

betaseries:
  url: https://www.betaseries.com/
  apiUrl: https://api.betaseries.com/
  apiVersion: '3.0'
  timeoutInSeconds: 10
  # client:
  #   plexAccount: ''
  #   clientId: ''
  #   clientSecret: ''
  # clients:
  #   {plexAccount}:
  #     clientId: ''
  #     clientSecret: ''
