name: Release

on:
  schedule:
    - cron: 0 6 * * *
      timezone: Europe/Paris
  workflow_dispatch:

env:
  NODE_VERSION: 24.x

jobs:
  semantic-release:
    name: Semantic release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    timeout-minutes: 10

    steps:
      - name: Generate a token
        id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # Get all tags

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        id: semantic
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        with:
          semantic_version: 25.0.3
          extra_plugins: conventional-changelog-conventionalcommits@9

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "### Release ${{ steps.semantic.outputs.new_release_version }} created :rocket:" >> $GITHUB_STEP_SUMMARY
